apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  selector:
    matchLabels:
      app: k8s-doc-example
  replicas: 2
  template:
    metadata:
      name: k8s-doc-example
      labels:
        app: k8s-doc-example
    spec:
      containers:
        - name: k8s-doc-example
          image: backend/containerdemo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  type: NodePort #type of service
  selector:
    app: k8s-doc-example
  ports:
    - name: http
      port: 8088 #where the service is running.
      targetPort: 8088 #the port exposed by the service.
