apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-ci-demo
  labels:
    app: devops-ci-demo
spec:
  selector:
    matchLabels:
      app: devops-ci-demo
  replicas: 1
  template:
    metadata:
      name: devops-ci-demo
      labels:
        app: devops-ci-demo
    spec:
      containers:
        - name: devops-ci-demo
          image: local/devops-ci-demo:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 8383 # The port that the container is running on in the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: devops-ci-demo
  labels:
    app: devops-ci-demo
spec:
  type: NodePort
  selector:
    app: devops-ci-demo
  ports:
    - name: http
      port: 8383 # The port that the service is running on in the cluster
      targetPort: 8383