apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-doc-example
  template:
    metadata:
      name: k8s-doc-example
      labels:
        app: k8s-doc-example
    spec:
      containers:
        - name: k8s-doc-example
          image: backend/containerdemo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
      restartPolicy: Always