on:
  push:
  workflow_dispatch:
    branches:
      - main
jobs:

  run_tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run all tests in project
        run: |
          mvn compile && mvn test
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: target/site/jacoco/
          retention-days: 7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.SECRET_NAME }}
      - name: Build and publish updated image
        run: |
          mvn package
          docker build . --tag ghcr.io/petrahrabakova/devops-ci-demo:latest
          docker push ghcr.io/petrahrabakova/devops-ci-demo:latest

  update_coverage_report:
    needs: run_tests
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/test_coverage_report.yaml

  trigger_cd_workflow:
    needs: [ update_coverage_report ] # Wait for the previous workflow to finish
    uses: ./.github/workflows/deploy-to-minikube.yaml
